/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "design.v:174.1-232.10" *)
module controller(clk, rst, start, enable, done);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "design.v:175.11-175.14" *)
  input clk;
  wire clk;
  (* src = "design.v:184.15-184.20" *)
  reg [2:0] count;
  (* src = "design.v:180.16-180.20" *)
  output done;
  reg done;
  (* src = "design.v:179.16-179.22" *)
  output enable;
  reg enable;
  (* src = "design.v:176.11-176.14" *)
  input rst;
  wire rst;
  (* src = "design.v:177.11-177.16" *)
  input start;
  wire start;
  (* onehot = 32'd1 *)
  reg [3:0] state;
  assign _06_ = ~count[2];
  assign _07_ = count[1] | count[0];
  assign _08_ = _07_ | _06_;
  assign _09_ = rst | ~(_08_);
  assign _10_ = state[1] & ~(_09_);
  assign _11_ = state[2] & ~(rst);
  assign _03_ = _11_ | _10_;
  assign _12_ = rst | start;
  assign _13_ = state[0] & ~(_12_);
  assign _14_ = _13_ | rst;
  assign _02_ = _14_ | state[3];
  assign _05_ = state[0] | state[3];
  assign _15_ = state[2] | state[0];
  assign _04_ = _15_ | state[1];
  assign _21_ = state[1] & ~(count[0]);
  assign _16_ = ~(count[1] ^ count[0]);
  assign _22_ = state[1] & ~(_16_);
  assign _17_ = count[1] & count[0];
  assign _18_ = _17_ ^ _06_;
  assign _23_ = state[1] & ~(_18_);
  assign _24_ = ~(_15_ | state[3]);
  assign _19_ = rst | ~(start);
  assign _00_ = state[0] & ~(_19_);
  assign _20_ = _08_ | rst;
  assign _01_ = state[1] & ~(_20_);
  always @(posedge clk)
    state[0] <= _02_;
  always @(posedge clk)
    state[1] <= _03_;
  always @(posedge clk)
    state[2] <= _00_;
  always @(posedge clk)
    state[3] <= _01_;
  (* src = "design.v:191.5-230.8" *)
  always @(posedge clk)
    if (rst) enable <= 1'h0;
    else enable <= _24_;
  (* src = "design.v:191.5-230.8" *)
  always @(posedge clk)
    if (rst) done <= 1'h0;
    else if (_05_) done <= state[3];
  (* src = "design.v:191.5-230.8" *)
  always @(posedge clk)
    if (rst) count[0] <= 1'h0;
    else if (_04_) count[0] <= _21_;
  (* src = "design.v:191.5-230.8" *)
  always @(posedge clk)
    if (rst) count[1] <= 1'h0;
    else if (_04_) count[1] <= _22_;
  (* src = "design.v:191.5-230.8" *)
  always @(posedge clk)
    if (rst) count[2] <= 1'h0;
    else if (_04_) count[2] <= _23_;
endmodule

(* src = "design.v:48.1-98.10" *)
module pe(clk, rst, enable, in_data, in_weight, out_data, out_weight, out_psum);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [15:0] _422_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11" *)
  wire [15:0] _423_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [15:0] _424_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:200.24-200.25" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] _425_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] _426_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [15:0] _427_;
  (* src = "design.v:49.11-49.14" *)
  input clk;
  wire clk;
  (* src = "design.v:62.16-62.24" *)
  reg [7:0] data_reg;
  (* src = "design.v:51.11-51.17" *)
  input enable;
  wire enable;
  (* src = "design.v:53.18-53.25" *)
  input [7:0] in_data;
  wire [7:0] in_data;
  (* src = "design.v:54.18-54.27" *)
  input [7:0] in_weight;
  wire [7:0] in_weight;
  (* src = "design.v:56.23-56.31" *)
  output [7:0] out_data;
  reg [7:0] out_data;
  (* src = "design.v:58.23-58.31" *)
  output [15:0] out_psum;
  reg [15:0] out_psum;
  (* src = "design.v:57.23-57.33" *)
  output [7:0] out_weight;
  reg [7:0] out_weight;
  (* src = "design.v:64.16-64.24" *)
  reg [15:0] psum_reg;
  (* src = "design.v:50.11-50.14" *)
  input rst;
  wire rst;
  (* src = "design.v:63.16-63.26" *)
  reg [7:0] weight_reg;
  assign _372_ = data_reg[3] & weight_reg[0];
  assign _373_ = _372_ ^ psum_reg[3];
  assign _374_ = ~(weight_reg[1] & data_reg[2]);
  assign _375_ = _374_ ^ _373_;
  assign _376_ = data_reg[2] & weight_reg[0];
  assign _377_ = ~(_376_ & psum_reg[2]);
  assign _378_ = weight_reg[1] & data_reg[1];
  assign _379_ = ~(_376_ ^ psum_reg[2]);
  assign _380_ = _378_ & ~(_379_);
  assign _381_ = _377_ & ~(_380_);
  assign _382_ = _381_ ^ _375_;
  assign _383_ = ~(weight_reg[2] & data_reg[1]);
  assign _384_ = weight_reg[3] & data_reg[0];
  assign _385_ = _384_ ^ _383_;
  assign _386_ = ~(_385_ ^ _382_);
  assign _387_ = ~(_379_ ^ _378_);
  assign _388_ = data_reg[1] & weight_reg[0];
  assign _389_ = ~(_388_ & psum_reg[1]);
  assign _390_ = weight_reg[1] & data_reg[0];
  assign _391_ = ~(_388_ ^ psum_reg[1]);
  assign _392_ = _390_ & ~(_391_);
  assign _393_ = _389_ & ~(_392_);
  assign _394_ = _393_ | ~(_387_);
  assign _395_ = weight_reg[2] & data_reg[0];
  assign _396_ = _393_ ^ _387_;
  assign _397_ = _395_ & ~(_396_);
  assign _398_ = _394_ & ~(_397_);
  assign _399_ = _398_ ^ _386_;
  assign _400_ = _396_ ^ _395_;
  assign _401_ = _391_ ^ _390_;
  assign _402_ = weight_reg[0] & data_reg[0];
  assign _403_ = _402_ & psum_reg[0];
  assign _404_ = _403_ & ~(_401_);
  assign _405_ = ~_404_;
  assign _406_ = _405_ | _400_;
  assign _425_[3] = _406_ ^ _399_;
  assign _407_ = data_reg[5] & weight_reg[0];
  assign _408_ = _407_ ^ psum_reg[5];
  assign _409_ = ~(weight_reg[1] & data_reg[4]);
  assign _410_ = _409_ ^ _408_;
  assign _411_ = data_reg[4] & weight_reg[0];
  assign _412_ = ~(_411_ & psum_reg[4]);
  assign _413_ = weight_reg[1] & data_reg[3];
  assign _414_ = ~(_411_ ^ psum_reg[4]);
  assign _415_ = _413_ & ~(_414_);
  assign _416_ = _412_ & ~(_415_);
  assign _417_ = _416_ ^ _410_;
  assign _418_ = weight_reg[2] & data_reg[3];
  assign _419_ = weight_reg[3] & data_reg[2];
  assign _420_ = _419_ ^ _418_;
  assign _421_ = ~(weight_reg[4] & data_reg[1]);
  assign _000_ = _421_ ^ _420_;
  assign _001_ = _000_ ^ _417_;
  assign _002_ = ~(_414_ ^ _413_);
  assign _003_ = ~(_372_ & psum_reg[3]);
  assign _004_ = _373_ & ~(_374_);
  assign _005_ = _003_ & ~(_004_);
  assign _006_ = _005_ | ~(_002_);
  assign _007_ = weight_reg[2] & data_reg[2];
  assign _008_ = weight_reg[3] & data_reg[1];
  assign _009_ = _008_ ^ _007_;
  assign _010_ = weight_reg[4] & data_reg[0];
  assign _011_ = _010_ ^ _009_;
  assign _012_ = _005_ ^ _002_;
  assign _013_ = _011_ & ~(_012_);
  assign _014_ = _006_ & ~(_013_);
  assign _015_ = _014_ ^ _001_;
  assign _016_ = ~(_008_ & _007_);
  assign _017_ = _010_ & _009_;
  assign _018_ = _016_ & ~(_017_);
  assign _019_ = weight_reg[5] & data_reg[0];
  assign _020_ = _019_ ^ _018_;
  assign _021_ = _020_ ^ _015_;
  assign _022_ = ~(_012_ ^ _011_);
  assign _023_ = _381_ | _375_;
  assign _024_ = _382_ & ~(_385_);
  assign _025_ = _023_ & ~(_024_);
  assign _026_ = _025_ | ~(_022_);
  assign _027_ = _384_ & ~(_383_);
  assign _028_ = _025_ ^ _022_;
  assign _029_ = _027_ & ~(_028_);
  assign _030_ = _026_ & ~(_029_);
  assign _031_ = _030_ ^ _021_;
  assign _032_ = _028_ ^ _027_;
  assign _033_ = _398_ | ~(_386_);
  assign _034_ = _033_ | _032_;
  assign _035_ = ~(_034_ ^ _031_);
  assign _036_ = ~(_033_ ^ _032_);
  assign _037_ = _406_ | _399_;
  assign _038_ = _037_ | _036_;
  assign _427_[5] = ~(_038_ ^ _035_);
  assign _039_ = data_reg[6] & weight_reg[0];
  assign _040_ = _039_ ^ psum_reg[6];
  assign _041_ = ~(weight_reg[1] & data_reg[5]);
  assign _042_ = _041_ ^ _040_;
  assign _043_ = ~(_407_ & psum_reg[5]);
  assign _044_ = _408_ & ~(_409_);
  assign _045_ = _043_ & ~(_044_);
  assign _046_ = _045_ ^ _042_;
  assign _047_ = ~(weight_reg[2] & data_reg[4]);
  assign _048_ = ~(weight_reg[3] & data_reg[3]);
  assign _049_ = _048_ ^ _047_;
  assign _050_ = ~(weight_reg[4] & data_reg[2]);
  assign _051_ = _050_ ^ _049_;
  assign _052_ = _051_ ^ _046_;
  assign _053_ = _416_ | _410_;
  assign _054_ = _417_ & ~(_000_);
  assign _055_ = _053_ & ~(_054_);
  assign _056_ = _055_ ^ _052_;
  assign _057_ = _419_ & _418_;
  assign _058_ = _420_ & ~(_421_);
  assign _059_ = _058_ | _057_;
  assign _060_ = weight_reg[5] & data_reg[1];
  assign _061_ = weight_reg[6] & data_reg[0];
  assign _062_ = ~(_061_ ^ _060_);
  assign _063_ = _062_ ^ _059_;
  assign _064_ = _063_ ^ _056_;
  assign _065_ = _014_ | _001_;
  assign _066_ = _015_ & ~(_020_);
  assign _067_ = _065_ & ~(_066_);
  assign _068_ = _067_ ^ _064_;
  assign _069_ = _019_ & ~(_018_);
  assign _070_ = ~_069_;
  assign _071_ = _070_ ^ _068_;
  assign _072_ = _030_ | _021_;
  assign _073_ = ~(_072_ ^ _071_);
  assign _074_ = _031_ & ~(_034_);
  assign _075_ = _035_ & ~(_038_);
  assign _076_ = _075_ | _074_;
  assign _427_[6] = ~(_076_ ^ _073_);
  assign _077_ = data_reg[7] & weight_reg[0];
  assign _078_ = _077_ ^ psum_reg[7];
  assign _079_ = ~(weight_reg[1] & data_reg[6]);
  assign _080_ = _079_ ^ _078_;
  assign _081_ = ~(_039_ & psum_reg[6]);
  assign _082_ = _040_ & ~(_041_);
  assign _083_ = _081_ & ~(_082_);
  assign _084_ = _083_ ^ _080_;
  assign _085_ = ~(weight_reg[2] & data_reg[5]);
  assign _086_ = ~(weight_reg[3] & data_reg[4]);
  assign _087_ = _086_ ^ _085_;
  assign _088_ = ~(weight_reg[4] & data_reg[3]);
  assign _089_ = _088_ ^ _087_;
  assign _090_ = _089_ ^ _084_;
  assign _091_ = _045_ | _042_;
  assign _092_ = _046_ & ~(_051_);
  assign _093_ = _091_ & ~(_092_);
  assign _094_ = _093_ ^ _090_;
  assign _095_ = _048_ | _047_;
  assign _096_ = _049_ & ~(_050_);
  assign _097_ = _095_ & ~(_096_);
  assign _098_ = ~(weight_reg[5] & data_reg[2]);
  assign _099_ = weight_reg[6] & data_reg[1];
  assign _100_ = ~(_099_ ^ _098_);
  assign _101_ = weight_reg[7] & data_reg[0];
  assign _102_ = ~_101_;
  assign _103_ = _102_ ^ _100_;
  assign _104_ = _103_ ^ _097_;
  assign _105_ = _061_ & _060_;
  assign _106_ = ~_105_;
  assign _107_ = _106_ ^ _104_;
  assign _108_ = _107_ ^ _094_;
  assign _109_ = _055_ | _052_;
  assign _110_ = _056_ & ~(_063_);
  assign _111_ = _109_ & ~(_110_);
  assign _112_ = _111_ ^ _108_;
  assign _113_ = _059_ & ~(_062_);
  assign _114_ = _113_ ^ _112_;
  assign _115_ = _067_ | _064_;
  assign _116_ = _068_ & ~(_070_);
  assign _117_ = _115_ & ~(_116_);
  assign _118_ = _117_ ^ _114_;
  assign _119_ = _072_ | _071_;
  assign _120_ = _076_ & ~(_073_);
  assign _121_ = _119_ & ~(_120_);
  assign _427_[7] = _121_ ^ _118_;
  assign _122_ = weight_reg[1] & data_reg[7];
  assign _123_ = ~(_122_ ^ psum_reg[8]);
  assign _124_ = ~(_077_ & psum_reg[7]);
  assign _125_ = _078_ & ~(_079_);
  assign _126_ = _124_ & ~(_125_);
  assign _127_ = _126_ ^ _123_;
  assign _128_ = ~(weight_reg[2] & data_reg[6]);
  assign _129_ = ~(weight_reg[3] & data_reg[5]);
  assign _130_ = _129_ ^ _128_;
  assign _131_ = ~(weight_reg[4] & data_reg[4]);
  assign _132_ = _131_ ^ _130_;
  assign _133_ = _132_ ^ _127_;
  assign _134_ = _083_ | _080_;
  assign _135_ = _084_ & ~(_089_);
  assign _136_ = _134_ & ~(_135_);
  assign _137_ = _136_ ^ _133_;
  assign _138_ = _086_ | _085_;
  assign _139_ = _087_ & ~(_088_);
  assign _140_ = _138_ & ~(_139_);
  assign _141_ = ~(weight_reg[5] & data_reg[3]);
  assign _142_ = weight_reg[6] & data_reg[2];
  assign _143_ = ~(_142_ ^ _141_);
  assign _144_ = weight_reg[7] & data_reg[1];
  assign _145_ = ~_144_;
  assign _146_ = _145_ ^ _143_;
  assign _147_ = _146_ ^ _140_;
  assign _148_ = _098_ | ~(_099_);
  assign _149_ = _100_ & ~(_102_);
  assign _150_ = _148_ & ~(_149_);
  assign _151_ = _150_ ^ _147_;
  assign _152_ = _151_ ^ _137_;
  assign _153_ = _093_ | _090_;
  assign _154_ = _094_ & ~(_107_);
  assign _155_ = _153_ & ~(_154_);
  assign _156_ = _155_ ^ _152_;
  assign _157_ = _103_ | _097_;
  assign _158_ = _104_ & ~(_106_);
  assign _159_ = _157_ & ~(_158_);
  assign _160_ = _159_ ^ _156_;
  assign _161_ = _111_ | _108_;
  assign _162_ = _113_ & _112_;
  assign _163_ = _161_ & ~(_162_);
  assign _164_ = ~(_163_ ^ _160_);
  assign _165_ = _114_ & ~(_117_);
  assign _166_ = ~(_119_ | _118_);
  assign _167_ = ~(_166_ | _165_);
  assign _168_ = _118_ | _073_;
  assign _169_ = _076_ & ~(_168_);
  assign _170_ = _169_ | ~(_167_);
  assign _427_[8] = ~(_170_ ^ _164_);
  assign _171_ = _122_ & psum_reg[8];
  assign _172_ = _171_ ^ psum_reg[9];
  assign _173_ = ~(weight_reg[2] & data_reg[7]);
  assign _174_ = weight_reg[3] & data_reg[6];
  assign _175_ = ~(_174_ ^ _173_);
  assign _176_ = weight_reg[4] & data_reg[5];
  assign _177_ = ~_176_;
  assign _178_ = _177_ ^ _175_;
  assign _179_ = _178_ ^ _172_;
  assign _180_ = _126_ | _123_;
  assign _181_ = _127_ & ~(_132_);
  assign _182_ = _180_ & ~(_181_);
  assign _183_ = _182_ ^ _179_;
  assign _184_ = _129_ | _128_;
  assign _185_ = _130_ & ~(_131_);
  assign _186_ = _184_ & ~(_185_);
  assign _187_ = ~(weight_reg[5] & data_reg[4]);
  assign _188_ = weight_reg[6] & data_reg[3];
  assign _189_ = _188_ ^ _187_;
  assign _190_ = weight_reg[7] & data_reg[2];
  assign _191_ = _190_ ^ _189_;
  assign _192_ = _191_ ^ _186_;
  assign _193_ = _141_ | ~(_142_);
  assign _194_ = _143_ & ~(_145_);
  assign _195_ = _193_ & ~(_194_);
  assign _196_ = _195_ ^ _192_;
  assign _197_ = _196_ ^ _183_;
  assign _198_ = _136_ | _133_;
  assign _199_ = _137_ & ~(_151_);
  assign _200_ = _198_ & ~(_199_);
  assign _201_ = _200_ ^ _197_;
  assign _202_ = _146_ | _140_;
  assign _203_ = _147_ & ~(_150_);
  assign _204_ = _202_ & ~(_203_);
  assign _205_ = ~(_204_ ^ _201_);
  assign _206_ = _155_ | _152_;
  assign _207_ = _156_ & ~(_159_);
  assign _208_ = _206_ & ~(_207_);
  assign _209_ = _208_ ^ _205_;
  assign _210_ = _163_ | _160_;
  assign _211_ = _170_ & ~(_164_);
  assign _212_ = _210_ & ~(_211_);
  assign _427_[9] = _212_ ^ _209_;
  assign _213_ = ~(weight_reg[3] & data_reg[7]);
  assign _214_ = weight_reg[4] & data_reg[6];
  assign _215_ = _214_ ^ _213_;
  assign _216_ = _215_ ^ psum_reg[10];
  assign _217_ = ~(_171_ & psum_reg[9]);
  assign _218_ = _172_ & ~(_178_);
  assign _219_ = _217_ & ~(_218_);
  assign _220_ = _219_ ^ _216_;
  assign _221_ = _173_ | ~(_174_);
  assign _222_ = _175_ & ~(_177_);
  assign _223_ = _221_ & ~(_222_);
  assign _224_ = weight_reg[5] & data_reg[5];
  assign _225_ = weight_reg[6] & data_reg[4];
  assign _226_ = ~(_225_ ^ _224_);
  assign _227_ = weight_reg[7] & data_reg[3];
  assign _228_ = _227_ ^ _226_;
  assign _229_ = _228_ ^ _223_;
  assign _230_ = _187_ | ~(_188_);
  assign _231_ = _190_ & ~(_189_);
  assign _232_ = _230_ & ~(_231_);
  assign _233_ = _232_ ^ _229_;
  assign _234_ = _233_ ^ _220_;
  assign _235_ = _182_ | _179_;
  assign _236_ = _183_ & ~(_196_);
  assign _237_ = _235_ & ~(_236_);
  assign _238_ = _237_ ^ _234_;
  assign _239_ = _191_ | _186_;
  assign _240_ = _192_ & ~(_195_);
  assign _241_ = _239_ & ~(_240_);
  assign _242_ = _241_ ^ _238_;
  assign _243_ = _200_ | _197_;
  assign _244_ = _201_ & ~(_204_);
  assign _245_ = _243_ & ~(_244_);
  assign _246_ = ~(_245_ ^ _242_);
  assign _247_ = _205_ & ~(_208_);
  assign _248_ = ~(_210_ | _209_);
  assign _249_ = _248_ | _247_;
  assign _250_ = _209_ | _164_;
  assign _251_ = _250_ | ~(_170_);
  assign _252_ = _251_ & ~(_249_);
  assign _427_[10] = _252_ ^ _246_;
  assign _253_ = ~psum_reg[11];
  assign _254_ = weight_reg[4] & data_reg[7];
  assign _255_ = _254_ ^ _253_;
  assign _256_ = psum_reg[10] & ~(_215_);
  assign _257_ = _256_ ^ _255_;
  assign _258_ = ~_257_;
  assign _259_ = _213_ | ~(_214_);
  assign _260_ = weight_reg[5] & data_reg[6];
  assign _261_ = weight_reg[6] & data_reg[5];
  assign _262_ = ~(_261_ ^ _260_);
  assign _263_ = weight_reg[7] & data_reg[4];
  assign _264_ = _263_ ^ _262_;
  assign _265_ = _264_ ^ _259_;
  assign _266_ = ~(_225_ & _224_);
  assign _267_ = _227_ & ~(_226_);
  assign _268_ = _266_ & ~(_267_);
  assign _269_ = _268_ ^ _265_;
  assign _270_ = _269_ ^ _258_;
  assign _271_ = _219_ | _216_;
  assign _272_ = _220_ & ~(_233_);
  assign _273_ = _271_ & ~(_272_);
  assign _274_ = _273_ ^ _270_;
  assign _275_ = _228_ | _223_;
  assign _276_ = _229_ & ~(_232_);
  assign _277_ = _275_ & ~(_276_);
  assign _278_ = _277_ ^ _274_;
  assign _279_ = _237_ | _234_;
  assign _280_ = _238_ & ~(_241_);
  assign _281_ = _279_ & ~(_280_);
  assign _282_ = ~(_281_ ^ _278_);
  assign _283_ = _245_ | _242_;
  assign _284_ = ~(_252_ | _246_);
  assign _285_ = _283_ & ~(_284_);
  assign _427_[11] = _285_ ^ _282_;
  assign _286_ = _254_ & ~(_253_);
  assign _287_ = ~(_286_ ^ psum_reg[12]);
  assign _288_ = ~_287_;
  assign _289_ = weight_reg[5] & data_reg[7];
  assign _290_ = weight_reg[6] & data_reg[6];
  assign _291_ = ~(_290_ ^ _289_);
  assign _292_ = weight_reg[7] & data_reg[5];
  assign _293_ = _292_ ^ _291_;
  assign _294_ = ~_293_;
  assign _295_ = ~(_261_ & _260_);
  assign _296_ = _263_ & ~(_262_);
  assign _297_ = _295_ & ~(_296_);
  assign _298_ = _297_ ^ _294_;
  assign _299_ = _298_ ^ _288_;
  assign _300_ = _255_ | ~(_256_);
  assign _301_ = _258_ & ~(_269_);
  assign _302_ = _300_ & ~(_301_);
  assign _303_ = ~(_302_ ^ _299_);
  assign _304_ = _264_ | _259_;
  assign _305_ = _265_ & ~(_268_);
  assign _306_ = _304_ & ~(_305_);
  assign _307_ = ~(_306_ ^ _303_);
  assign _308_ = _273_ | _270_;
  assign _309_ = _274_ & ~(_277_);
  assign _310_ = _308_ & ~(_309_);
  assign _311_ = ~(_310_ ^ _307_);
  assign _312_ = _281_ | _278_;
  assign _313_ = ~(_283_ | _282_);
  assign _314_ = _312_ & ~(_313_);
  assign _315_ = _282_ | _246_;
  assign _316_ = _249_ & ~(_315_);
  assign _317_ = _314_ & ~(_316_);
  assign _318_ = _315_ | _250_;
  assign _319_ = _170_ & ~(_318_);
  assign _320_ = _317_ & ~(_319_);
  assign _427_[12] = _320_ ^ _311_;
  assign _321_ = weight_reg[6] & data_reg[7];
  assign _322_ = weight_reg[7] & data_reg[6];
  assign _323_ = ~(_322_ ^ _321_);
  assign _324_ = ~_323_;
  assign _325_ = ~(_290_ & _289_);
  assign _326_ = _292_ & ~(_291_);
  assign _327_ = _325_ & ~(_326_);
  assign _328_ = _327_ ^ _324_;
  assign _329_ = _328_ ^ psum_reg[13];
  assign _330_ = ~(_286_ & psum_reg[12]);
  assign _331_ = _288_ & ~(_298_);
  assign _332_ = _330_ & ~(_331_);
  assign _333_ = ~(_332_ ^ _329_);
  assign _334_ = _294_ & ~(_297_);
  assign _335_ = _334_ ^ _333_;
  assign _336_ = _302_ | _299_;
  assign _337_ = ~(_306_ | _303_);
  assign _338_ = _336_ & ~(_337_);
  assign _339_ = ~(_338_ ^ _335_);
  assign _340_ = _310_ | _307_;
  assign _341_ = ~(_320_ | _311_);
  assign _342_ = _340_ & ~(_341_);
  assign _427_[13] = _342_ ^ _339_;
  assign _343_ = weight_reg[7] & data_reg[7];
  assign _344_ = _322_ & _321_;
  assign _345_ = ~(_344_ ^ _343_);
  assign _346_ = _345_ ^ psum_reg[14];
  assign _347_ = psum_reg[13] & ~(_328_);
  assign _348_ = _347_ ^ _346_;
  assign _349_ = _324_ & ~(_327_);
  assign _350_ = _349_ ^ _348_;
  assign _351_ = _332_ | _329_;
  assign _352_ = _334_ & ~(_333_);
  assign _353_ = _351_ & ~(_352_);
  assign _354_ = ~(_353_ ^ _350_);
  assign _355_ = _338_ | _335_;
  assign _356_ = ~(_340_ | _339_);
  assign _357_ = _355_ & ~(_356_);
  assign _358_ = _339_ | _311_;
  assign _359_ = ~(_358_ | _320_);
  assign _360_ = _357_ & ~(_359_);
  assign _427_[14] = _360_ ^ _354_;
  assign _361_ = psum_reg[14] & ~(_345_);
  assign _362_ = _361_ ^ psum_reg[15];
  assign _363_ = _344_ & _343_;
  assign _364_ = _363_ ^ _362_;
  assign _365_ = _346_ | ~(_347_);
  assign _366_ = _349_ & ~(_348_);
  assign _367_ = _365_ & ~(_366_);
  assign _368_ = _367_ ^ _364_;
  assign _369_ = _353_ | _350_;
  assign _370_ = ~(_360_ | _354_);
  assign _371_ = _369_ & ~(_370_);
  assign _427_[15] = _371_ ^ _368_;
  assign _426_[4] = _037_ ^ _036_;
  assign _422_[0] = _402_ ^ psum_reg[0];
  assign _423_[1] = ~(_403_ ^ _401_);
  assign _424_[2] = _405_ ^ _400_;
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_data[0] <= 1'h0;
    else if (enable) out_data[0] <= data_reg[0];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_data[1] <= 1'h0;
    else if (enable) out_data[1] <= data_reg[1];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_data[2] <= 1'h0;
    else if (enable) out_data[2] <= data_reg[2];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_data[3] <= 1'h0;
    else if (enable) out_data[3] <= data_reg[3];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_data[4] <= 1'h0;
    else if (enable) out_data[4] <= data_reg[4];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_data[5] <= 1'h0;
    else if (enable) out_data[5] <= data_reg[5];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_data[6] <= 1'h0;
    else if (enable) out_data[6] <= data_reg[6];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_data[7] <= 1'h0;
    else if (enable) out_data[7] <= data_reg[7];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_weight[0] <= 1'h0;
    else if (enable) out_weight[0] <= weight_reg[0];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_weight[1] <= 1'h0;
    else if (enable) out_weight[1] <= weight_reg[1];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_weight[2] <= 1'h0;
    else if (enable) out_weight[2] <= weight_reg[2];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_weight[3] <= 1'h0;
    else if (enable) out_weight[3] <= weight_reg[3];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_weight[4] <= 1'h0;
    else if (enable) out_weight[4] <= weight_reg[4];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_weight[5] <= 1'h0;
    else if (enable) out_weight[5] <= weight_reg[5];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_weight[6] <= 1'h0;
    else if (enable) out_weight[6] <= weight_reg[6];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_weight[7] <= 1'h0;
    else if (enable) out_weight[7] <= weight_reg[7];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[0] <= 1'h0;
    else if (enable) out_psum[0] <= psum_reg[0];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[1] <= 1'h0;
    else if (enable) out_psum[1] <= psum_reg[1];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[2] <= 1'h0;
    else if (enable) out_psum[2] <= psum_reg[2];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[3] <= 1'h0;
    else if (enable) out_psum[3] <= psum_reg[3];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[4] <= 1'h0;
    else if (enable) out_psum[4] <= psum_reg[4];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[5] <= 1'h0;
    else if (enable) out_psum[5] <= psum_reg[5];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[6] <= 1'h0;
    else if (enable) out_psum[6] <= psum_reg[6];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[7] <= 1'h0;
    else if (enable) out_psum[7] <= psum_reg[7];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[8] <= 1'h0;
    else if (enable) out_psum[8] <= psum_reg[8];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[9] <= 1'h0;
    else if (enable) out_psum[9] <= psum_reg[9];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[10] <= 1'h0;
    else if (enable) out_psum[10] <= psum_reg[10];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[11] <= 1'h0;
    else if (enable) out_psum[11] <= psum_reg[11];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[12] <= 1'h0;
    else if (enable) out_psum[12] <= psum_reg[12];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[13] <= 1'h0;
    else if (enable) out_psum[13] <= psum_reg[13];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[14] <= 1'h0;
    else if (enable) out_psum[14] <= psum_reg[14];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) out_psum[15] <= 1'h0;
    else if (enable) out_psum[15] <= psum_reg[15];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) data_reg[0] <= 1'h0;
    else if (enable) data_reg[0] <= in_data[0];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) data_reg[1] <= 1'h0;
    else if (enable) data_reg[1] <= in_data[1];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) data_reg[2] <= 1'h0;
    else if (enable) data_reg[2] <= in_data[2];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) data_reg[3] <= 1'h0;
    else if (enable) data_reg[3] <= in_data[3];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) data_reg[4] <= 1'h0;
    else if (enable) data_reg[4] <= in_data[4];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) data_reg[5] <= 1'h0;
    else if (enable) data_reg[5] <= in_data[5];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) data_reg[6] <= 1'h0;
    else if (enable) data_reg[6] <= in_data[6];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) data_reg[7] <= 1'h0;
    else if (enable) data_reg[7] <= in_data[7];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) weight_reg[0] <= 1'h0;
    else if (enable) weight_reg[0] <= in_weight[0];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) weight_reg[1] <= 1'h0;
    else if (enable) weight_reg[1] <= in_weight[1];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) weight_reg[2] <= 1'h0;
    else if (enable) weight_reg[2] <= in_weight[2];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) weight_reg[3] <= 1'h0;
    else if (enable) weight_reg[3] <= in_weight[3];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) weight_reg[4] <= 1'h0;
    else if (enable) weight_reg[4] <= in_weight[4];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) weight_reg[5] <= 1'h0;
    else if (enable) weight_reg[5] <= in_weight[5];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) weight_reg[6] <= 1'h0;
    else if (enable) weight_reg[6] <= in_weight[6];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) weight_reg[7] <= 1'h0;
    else if (enable) weight_reg[7] <= in_weight[7];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[0] <= 1'h0;
    else if (enable) psum_reg[0] <= _422_[0];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[1] <= 1'h0;
    else if (enable) psum_reg[1] <= _423_[1];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[2] <= 1'h0;
    else if (enable) psum_reg[2] <= _424_[2];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[3] <= 1'h0;
    else if (enable) psum_reg[3] <= _425_[3];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[4] <= 1'h0;
    else if (enable) psum_reg[4] <= _426_[4];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[5] <= 1'h0;
    else if (enable) psum_reg[5] <= _427_[5];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[6] <= 1'h0;
    else if (enable) psum_reg[6] <= _427_[6];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[7] <= 1'h0;
    else if (enable) psum_reg[7] <= _427_[7];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[8] <= 1'h0;
    else if (enable) psum_reg[8] <= _427_[8];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[9] <= 1'h0;
    else if (enable) psum_reg[9] <= _427_[9];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[10] <= 1'h0;
    else if (enable) psum_reg[10] <= _427_[10];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[11] <= 1'h0;
    else if (enable) psum_reg[11] <= _427_[11];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[12] <= 1'h0;
    else if (enable) psum_reg[12] <= _427_[12];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[13] <= 1'h0;
    else if (enable) psum_reg[13] <= _427_[13];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[14] <= 1'h0;
    else if (enable) psum_reg[14] <= _427_[14];
  (* src = "design.v:71.5-96.8" *)
  always @(posedge clk)
    if (rst) psum_reg[15] <= 1'h0;
    else if (enable) psum_reg[15] <= _427_[15];
  assign _422_[15:9] = psum_reg[15:9];
  assign { _423_[15:12], _423_[0] } = { psum_reg[15:12], _422_[0] };
  assign { _424_[15], _424_[1:0] } = { psum_reg[15], _423_[1], _422_[0] };
  assign _425_[2:0] = { _424_[2], _423_[1], _422_[0] };
  assign _426_[3:0] = { _425_[3], _424_[2], _423_[1], _422_[0] };
  assign _427_[4:0] = { _426_[4], _425_[3], _424_[2], _423_[1], _422_[0] };
endmodule

(* src = "design.v:100.1-172.10" *)
module systolic_array_2x2(clk, rst, enable, data_in_0, data_in_1, weight_in_0, weight_in_1, out_00, out_01, out_10, out_11);
  (* src = "design.v:101.11-101.14" *)
  input clk;
  wire clk;
  (* src = "design.v:118.16-118.25" *)
  wire [7:0] d00_to_01;
  (* src = "design.v:119.16-119.25" *)
  wire [7:0] d10_to_11;
  (* src = "design.v:105.18-105.27" *)
  input [7:0] data_in_0;
  wire [7:0] data_in_0;
  (* src = "design.v:106.18-106.27" *)
`  input [7:0] data_in_1;
  wire [7:0] data_in_1;
  (* src = "design.v:103.11-103.17" *)
  input enable;
  wire enable;
  (* src = "design.v:111.19-111.25" *)
  output [15:0] out_00;
  wire [15:0] out_00;
  (* src = "design.v:112.19-112.25" *)
  output [15:0] out_01;
  wire [15:0] out_01;
  (* src = "design.v:113.19-113.25" *)
  output [15:0] out_10;
  wire [15:0] out_10;
  (* src = "design.v:114.19-114.25" *)
  output [15:0] out_11;
  wire [15:0] out_11;
  (* src = "design.v:102.11-102.14" *)
  input rst;
  wire rst;
  (* src = "design.v:121.16-121.25" *)
  wire [7:0] w00_to_10;
  (* src = "design.v:122.16-122.25" *)
  wire [7:0] w01_to_11;
  (* src = "design.v:108.18-108.29" *)
  input [7:0] weight_in_0;
  wire [7:0] weight_in_0;
  (* src = "design.v:109.18-109.29" *)
  input [7:0] weight_in_1;
  wire [7:0] weight_in_1;
  (* module_not_derived = 32'd1 *)
  (* src = "design.v:125.8-134.6" *)
  pe PE00 (
    .clk(clk),
    .enable(enable),
    .in_data(data_in_0),
    .in_weight(weight_in_0),
    .out_data(d00_to_01),
    .out_psum(out_00),
    .out_weight(w00_to_10),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "design.v:137.8-146.6" *)
  pe PE01 (
    .clk(clk),
    .enable(enable),
    .in_data(d00_to_01),
    .in_weight(weight_in_1),
    .out_psum(out_01),
    .out_weight(w01_to_11),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "design.v:149.8-158.6" *)
  pe PE10 (
    .clk(clk),
    .enable(enable),
    .in_data(data_in_1),
    .in_weight(w00_to_10),
    .out_data(d10_to_11),
    .out_psum(out_10),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "design.v:161.8-170.6" *)
  pe PE11 (
    .clk(clk),
    .enable(enable),
    .in_data(d10_to_11),
    .in_weight(w01_to_11),
    .out_psum(out_11),
    .rst(rst)
  );
endmodule

(* top =  1  *)
(* src = "design.v:1.1-46.10" *)
module top(clk, rst, start, data_in_0, data_in_1, weight_in_0, weight_in_1, out_00, out_01, out_10, out_11, done);
  (* src = "design.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "design.v:6.18-6.27" *)
  input [7:0] data_in_0;
  wire [7:0] data_in_0;
  (* src = "design.v:7.18-7.27" *)
  input [7:0] data_in_1;
  wire [7:0] data_in_1;
  (* src = "design.v:17.12-17.16" *)
  output done;
  wire done;
  (* src = "design.v:20.10-20.16" *)
  wire enable;
  (* src = "design.v:12.19-12.25" *)
  output [15:0] out_00;
  wire [15:0] out_00;
  (* src = "design.v:13.19-13.25" *)
  output [15:0] out_01;
  wire [15:0] out_01;
  (* src = "design.v:14.19-14.25" *)
  output [15:0] out_10;
  wire [15:0] out_10;
  (* src = "design.v:15.19-15.25" *)
  output [15:0] out_11;
  wire [15:0] out_11;
  (* src = "design.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "design.v:4.11-4.16" *)
  input start;
  wire start;
  (* src = "design.v:9.18-9.29" *)
  input [7:0] weight_in_0;
  wire [7:0] weight_in_0;
  (* src = "design.v:10.18-10.29" *)
  input [7:0] weight_in_1;
  wire [7:0] weight_in_1;
  (* module_not_derived = 32'd1 *)
  (* src = "design.v:23.16-29.6" *)
  controller ctrl (
    .clk(clk),
    .done(done),
    .enable(enable),
    .rst(rst),
    .start(start)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "design.v:32.24-44.6" *)
  systolic_array_2x2 sa (
    .clk(clk),
    .data_in_0(data_in_0),
    .data_in_1(data_in_1),
    .enable(enable),
    .out_00(out_00),
    .out_01(out_01),
    .out_10(out_10),
    .out_11(out_11),
    .rst(rst),
    .weight_in_0(weight_in_0),
    .weight_in_1(weight_in_1)
  );
endmodule
